### PR TITLE
Add support for filter runs by sha1 

### PR DESCRIPTION
**Pull request by kshtsk**
Implements https://tracker.ceph.com/issues/46805

### CODE REVIEW

**Comment by kshtsk** [comment]
retest this please

**Review by yuriw — APPROVED** [review]
Need code review from @tchaikov

**Review by jdurgin — APPROVED** [review]

**Comment by yuriw** [comment]
@kshtsk 
@tchaikov is OoO this week, @jdurgin approved, so merge at will

**Comment by djgalloway** [comment]
@yuriw in order to deploy this, we'd have to pause the queue and wait for running jobs to stop.  I'll leave it up to you when we can afford to do that.

**Pull request merged**
