### PR TITLE
requirements.txt: bump up psycopg2

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@zmc @djgalloway guys, review please?

**Comment by tchaikov** [comment]
why? the newer the merrier?

**Comment by kshtsk** [comment]
This current version does not work for me on openSUSE:
```    ERROR: Command errored out with exit status 1:
     command: /home/kyr/kshtsk/paddles/v/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4O1gZM/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4O1gZM/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-4O1gZM/psycopg2/
    Complete output (14 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kshtsk** [comment]
The newer version of pg_config at all. Also even if install the devel package of postgresql where the pg_config resides, the 2.6.1 fails with error:
```
     command: /home/kyr/kshtsk/paddles/v/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dUp6lS/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dUp6lS/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-dUp6lS/psycopg2/
    Complete output (7 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.10'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tchaikov** [comment]
i think it still needs `pg_config`. see http://initd.org/psycopg/docs/install.html#install-from-source

**Comment by kshtsk** [comment]
> i think it still needs `pg_config`. see http://initd.org/psycopg/docs/install.html#install-from-source

I can agree, but this is not required when installing not from the source code... in the newer version I guess they fixed this issue. As I said, it can not be installed even after I install the devel package with pg_config. The newer version works fine for me... Paddles is deployed and works with postgresql without problems.

**Comment by tchaikov** [comment]
could you update the commit message to explain why we want to bump the required psycopg2 version?

> postresql: update dependency 

is not accurate and is misleading.

i think a better one is something like

> requirements.txt: bump up psycopg2
>
> psycopg2 v2.6.1 does not support postresql 10
> see https://github.com/psycopg/psycopg2/issues/489
>

**Comment by tchaikov** [comment]
also, any reason not using the latest stable, say, 2.8.3?

**Comment by kshtsk** [comment]
> also, any reason not using the latest stable, say, 2.8.3?

I took the first working version for me at that time, and it tested for more than 2 months.
So the only reason of taking 2.8.3 is that I haven't tested it at all.

**Comment by kshtsk** [comment]
> i think a better one is something like
> 
> > requirements.txt: bump up psycopg2
> > psycopg2 v2.6.1 does not support postresql 10
> > see [psycopg/psycopg2#489](https://github.com/psycopg/psycopg2/issues/489)

DONE

**Comment by kshtsk** [comment]
@tchaikov oh... sorry, this patch is dated by 7 May, so it has been working for me for 5 months.

**Pull request merged**
