### PR TITLE
NodeController: Add delete() method

### PR DESCRIPTION
**Pull request by zmc**
We need to be able to clean up things like this: https://pulpito.ceph.com/nodes/?machine_type=testnode

### CODE REVIEW

**Review by amathuria — APPROVED** [review]
Nice! LGTM 
So we would have to trigger this periodically?

**Comment by dmick** [comment]
@amathuria no, this just provides an API endpoint for delete.  Something like curl would be used to call it.

**Review by akraitman — APPROVED** [review]

**Comment by zmc** [comment]
I just deployed the new image:
```
zack@pulpito:~$ docker service update --image quay.io/ceph-infra/paddles:main paddles --force
paddles
overall progress: 10 out of 10 tasks
1/10: running   [==================================================>]
2/10: running   [==================================================>]
3/10: running   [==================================================>]
4/10: running   [==================================================>]
5/10: running   [==================================================>]
6/10: running   [==================================================>]
7/10: running   [==================================================>]
8/10: running   [==================================================>]
9/10: running   [==================================================>]
10/10: running   [==================================================>]
verify: Service converged
```

**Comment by dmick** [comment]
👍

**Pull request merged**
