### PR TITLE
DNM: Avoid some unnecessary db load

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by zmc** [comment]
@susebot run deploy

**Comment by zmc** [comment]
@kshtsk did I ask for the deploy test wrong? or is there a whitelist I'm not on?

**Comment by kshtsk** [comment]
> @kshtsk did I ask for the deploy test wrong? or is there a whitelist I'm not on?

You did ask right, but it is only configured for teuthology repo, there is no job for pulpito or paddles repos yet.

**Comment by zmc** [comment]
I found an issue with my approach; going to close this and reopen a different one with more fixes soon.

**Pull request closed without merging**
